#!/usr/bin/env bash

# Created by pinkSakoora (https://github.com/pinkSakoora)
# Last changed: 19/07/26

export S_PATH="$(dirname "$(readlink -f "$0")")"
S_HYPRPATH="$HOME"/.config/hypr
NUM_STYLES=2
source "$S_PATH"/flaglist

# The flow is as follows:
# Check for dependencies (hyprlock, hyprland, imagemagick, grim, bluez-utils (for bluetoothctl), NetworkManager, playerctl)
# Install when needed, send Ok otherwise
# Check if hyprland is running (PRINTENV)
# Select style(s) to install
# Run the size selection and file creation
# Move the required scripts
# Post install messages

ok() { echo "✔ " "$@"; }
cross() { echo "✖ " "$@"; }
part_done() { sed -i "s/$1=0/$1=1/" "$S_PATH/flaglist"; }

confirm() {
	local response default=${2:-"Y"}					# default is Y if no argument sent
	[ "$default" = "Y" ] && local responsebox="[Y/n]"	# Set responsebox to [Y/n] if no prompt
	while true; do
		read -rp "$1 ${responsebox:-'[y/N]'}: " response	# If responsebox wasn't set then respbox is [y/N]
		response="${response:-$default}"					# If response wasn't input then it's default
		case $response in
			[Yy]* ) return 0;;
			[Nn]* ) return 1;;
			* ) echo "Invalid input.";;
		esac
	done
}

execute() {
	"$@"
	exitcode=${PIPESTATUS[0]}
	return "$exitcode"
}

command_fail(){
	case "$1" in
		1 ) cross "Failed to install dependencies. Pacman exit code: $exitcode";;
		2 ) cross "Could not find $S_HYPRPATH. [S_HYPRPATH not found: $1]";;
		3 ) cross "Hyprland is currently not running, launch Hyprland to continue. [Hyprland not running: $1]";;
		4 ) cross "Exiting installer on user prompt. [Package installation abort: $1]";;
		5 ) cross "Exiting installer on user prompt. [Pre-installation abort: $1]";;
		6 ) cross "Style script (at $S_PATH/style-$style) does not exist or is not executable. [File error: $1]";;
		7 ) cross "Style script (at $S_PATH/style-$style) encountered an error during execution. [Execution error: $1]";;
		8 ) cross "Failed to create directory. Permission denied or path invalid. [Filesystem error: $1]";;
		9 | 10 ) cross "Failed to move files. Source missing or permission denied. [Filesystem error: $1]";;
	esac
	exit "$1"
}

show_progress() {
	echo "Progress:"
	if [ "$S_DEPS" -eq 0 ]; then
		cross "Dependencies not installed."
	else
		ok "Dependencies installed."
	fi
	if [ "$S_SETUP" -eq 0 ]; then
		cross "Hyprlock configuration not set up."
	else
		ok "Hyprlock configuration set up."
	fi
	if [ "$S_MOVED" -eq 0 ]; then
		cross "Hyprlock configuration and scripts not moved."
	else
		ok "Hyprlock configuration and scripts moved."
	fi
}

check_deps() {
	deps=("hyprland" "hyprlock" "imagemagick" "grim" "bluez-utils" "networkmanager" "playerctl")
	not_installed=()
	echo "Checking for dependencies..."
	for dep in "${deps[@]}"; do
		if pacman -Q | grep -q "$dep"; then
			ok "$dep"
		else
			cross "$dep"
			not_installed+=("$dep")
		fi
	done
}

install_deps() {
	if [ ${#not_installed[@]} -eq 0 ]; then
		echo "All required packages are already installed."
		part_done "S_DEPS"
		return
	fi
	echo -en "The following packages need to be installed before proceeding:\n ${not_installed[*]}"
	if confirm "Proceed?"; then
		execute sudo pacman -Syu --noconfirm --noprogressbar "${not_installed[*]}" || command_fail 1
	else
		command_fail 4
	fi
	part_done "S_DEPS"
}

setup_hyprlock() {
	export width
	export height
	export pw
	export pp
	resolution=$(hyprctl monitors | grep -m1 -oP '\S.{1,}(?=@)')
	width=$(echo "$resolution" | cut -dx -f1)
	height=$(echo "$resolution" | cut -dx -f2)
	[ $((4*height/9)) -ge $((width/4)) ] && pw=$((width/4)) || pw=$((4*height/9))
	pp=$((pw/12))

	while true; do
		read -rp "Select styles to set up (available: $NUM_STYLES, default: all): (eg: \"1 2 3\", \"2-4\") " input
		input=${input:="1-$NUM_STYLES"}
		for part in $input; do
			if [[ $part =~ ^([0-9]+)-([0-9]+)$ ]]; then
				first=${BASH_REMATCH[1]}
				last=${BASH_REMATCH[2]}
				if (( first < 1 || last > NUM_STYLES || first > last )); then
					echo "Invalid input. $part is out of bounds (1-$NUM_STYLES)."
					break
				fi
				for (( n=first; n<=last; n++ )); do
					styles+=("$n")
				done
			elif [[ $part =~ ^[0-9]+$ ]]; then
				if (( part >= 1 && part <= NUM_STYLES )); then
					styles+=("$part")
				else
					echo "Invalid input. $part is out of bounds (1-$NUM_STYLES)."
					break
				fi
			fi
		done
		if [ ${#styles[@]} -gt 0 ]; then
			break	
		fi
	done

	echo "Styles to be set up: ${styles[*]}"
	for style in "${styles[@]}"; do
		[ ! -x "$S_PATH/style-$style" ] && command_fail 6
		"$S_PATH/style-$style" || command_fail 7
	done
	
	if [ ${#styles[@]} -eq 1 ]; then
		default_style="${styles[0]}"
		echo "Only one style set up. Defaulting to style-$default_style."
	else
		while true; do
			read -rp "Select default style: ${styles[*]} " default_style
			if [[ " ${styles[*]} " =~ $default_style ]] && [[ -n "$default_style" ]]; then
				break
			else
				echo "Invalid input."
			fi
		done
	fi
	echo "Setting style-$default_style as default."

	part_done "S_SETUP"
}

move_files() {
	mkdir -p "$HOME"/.local/share/fonts/ttf || command_fail 8
	mv -b "$S_PATH"/to_move/*.ttf "$HOME"/.local/share/fonts/ttf/ || command_fail 9
	ok "Moved fonts to $HOME/.local/share/fonts/ttf/"
	if [ -d "$S_HYPRPATH" ]; then
		for file in "$S_PATH"/to_move/*; do
			mv -b --suffix="-pre-sakoora" "$file" "$S_HYPRPATH" || command_fail 10
			ok "$file moved to $S_HYPRPATH"
		done
	else
		command_fail 2
	fi

	S_SAKOORA="$S_HYPRPATH/sakoora.hyprlock"
	S_LOCK="$S_HYPRPATH/hyprlock.conf"
	S_SOURCE="source = $S_SAKOORA/current_style.conf"

	ln -sf "$S_SAKOORA/style-$default_style/hyprlock.conf" "$S_SAKOORA/current_style.conf" || command_fail 11

	if [ -L "$S_LOCK" ]; then
		echo "$S_LOCK is currently a symlink."
		mv "$S_LOCK" "$S_LOCK-pre-sakoora"
		echo -e "\n# sakoora.hyprlock\n$S_SOURCE" >> "$S_LOCK"
		ok "Replaced symlink with config (at $S_LOCK). Old symlink stored at $S_LOCK-pre-sakoora."
	elif [ -f "$S_LOCK" ]; then
		if ! grep -Fxq "$S_SOURCE" "$S_LOCK"; then
			echo -e "\n# sakoora.hyprlock\n$S_SOURCE" >> "$S_LOCK"
			ok "Added sakoora.hyprlock entry to existing hyprlock config (at $S_LOCK)"
		fi
	else
		echo -e "# sakoora.hyprlock\n$S_SOURCE" > "$S_LOCK"
		ok "Created hyprlock config file at $S_LOCK"
	fi

	part_done "S_MOVED"
}

clear
show_progress
if [ "$((S_DEPS+S_SETUP+S_MOVED))" -eq 3 ]; then
	echo "Installation has already been completed!"
	exit
elif ! confirm "Proceed with installation?"; then
	command_fail 5
fi
if [ "$S_DEPS" -eq 0 ]; then
	check_deps
	install_deps
fi
printenv HYPRLAND_INSTANCE_SIGNATURE &> /dev/null || command_fail 3
if [ "$S_SETUP" -eq 0 ]; then
	setup_hyprlock
fi
if [ "$S_MOVED" -eq 0 ]; then
	move_files
fi
echo "Installation completed!"
