#!/usr/bin/env bash

source "$HOME"/.config/hypr/sakoora.hyprlock/colors-hyprlock.sh

current_time() {
	echo "It is <span foreground='$color2'>$(date +%H:%M)</span>."
}

day_date() {
	echo "Today is <span foreground='$color2'>$(date +%A,\ %d\ %B\ %Y)</span>."
}

power_status() {
	if [ $desktop -eq 1 ]; then
		echo "Desktop has been <span foreground='$color2'>$(uptime -p)</span>."
	else
		echo "Battery is at <span foreground='$color2'>$(cat /sys/class/power_supply/BAT1/capacity)%</span> and <span foreground='$color2'>$(cat /sys/class/power_supply/BAT1/status | tr '[:upper:]' '[:lower:]')</span>."
	fi
}

if hostnamectl | grep -q "Chassis: laptop"; then
	desktop=0
else
	desktop=1
fi

case "$1" in
	"-1" )
		current_time;;
	"-2" )
		day_date;;
	"-3" )
		power_status;;
esac
